### PR TITLE
Adding Legacy Token in token registry

### PR DESCRIPTION
**Pull request by paulaamstutz**

### CODE REVIEW

**Review by XJWX89 — CHANGES_REQUESTED** [review]
hi @paulaamstutz , 
1. Contract address start with 0x + 40 characters and **must be lower case** (mainnet & testnet)
2. Please remove unsupported links in `additional.json` file (mainnet & testnet).

**Comment by paulaamstutz** [comment]
I have renamed my token in lowercases (mainnet and testnet) and removed the unsupported links in additional.json

**Review by XJWX89 — CHANGES_REQUESTED** [review]
hi @paulaamstutz ,
1. Token image  must be named it `token.png`.(Image must be **png** format, transparent background and **256 x 256** pixel size)
2. There are two contract address directory  in the testnet

**Comment by paulaamstutz** [comment]
Hello @XJWX89 ,
I made the changes you required.

**Review by XJWX89 — APPROVED** [review]

**Pull request merged**
