### PR TITLE
Listing $Lion token

### PR DESCRIPTION
**Pull request by LIONBABYCRYPTO**
Add $Lion

### CODE REVIEW

**Comment by LIONBABYCRYPTO** [comment]
What was the error ?

**Comment by VetMaik** [comment]
@LIONBABYCRYPTO you need to remove the comma after you GitHub row.

 "github":"https://github.com/lionbabycrypto",
Remove the comma from the upper line and it should be fine

**Comment by LIONBABYCRYPTO** [comment]
Thank God ! It Passed finally ! Lol

**Review by XJWX89 — CHANGES_REQUESTED** [review]
hi @LIONBABYCRYPTO  , token symbol should be `LION`

**Comment by LIONBABYCRYPTO** [comment]
It’s done !

**Comment by LIONBABYCRYPTO** [comment]
Please let me know what else I can do to have it to merge ! Thank you !

**Comment by LIONBABYCRYPTO** [comment]
Anyone knows if the merge will happen soon ?

**Review by libotony — APPROVED** [review]

**Comment by LIONBABYCRYPTO** [comment]
Thank you for the approval !

**Pull request merged**
