### PR TITLE
Initial Commit of Banana Coin

### PR DESCRIPTION
**Pull request by Murtagh300**
MemeCoin, GG Gangster Gorillas no roadmap, no utility Lots of potential.

### CODE REVIEW

**Comment by Murtagh300** [comment]
@libotony @XJWX89 Srry for tagging you guys

**Review by XJWX89 — CHANGES_REQUESTED** [review]
hi @Murtagh300 , 
sorry for the late review, unfortunately  this pr need some change
1. Please make sure the directory name is in **lower cases** (the contract address on main/test )
2. Please upload the **token image**.
3. The website you provided is unreachable . could you check it ?
4. The `links` you provided should be **twitter** instead of *github*

**Comment by Murtagh300** [comment]
Please make sure the directory name is in lower cases (the contract address on main/test ) **Done**
Please upload the token image. **Done**
The website you provided is unreachable . could you check it ? **Website still in development**
The links you provided should be twitter instead of github **Done**

**Comment by libotony** [comment]
@Murtagh300 Looks like you have **removed all token images**, I would suggest re-open a new PR in a new branch, which is the most convenient way.

**Pull request closed without merging**
