### PR TITLE
Add yeet

### PR DESCRIPTION
**Pull request by douwefa**
Adding YEET

### CODE REVIEW

**Comment by XJWX89** [comment]
hi @douwefa , just wondering that the image is correct , because it is not transparent .  it may cause some application flexibility of using the image .

**Comment by douwefa** [comment]
> hi @douwefa , just wondering the image is correct, because it is not transparent. It may cause some application flexibility of using the image.

You're right, what is the best way to change that? New pull request?

**Comment by libotony** [comment]
@douwefa You can  append requests to your master branch, the new commit will automatically add to this request

**Comment by douwefa** [comment]
> @douwefa You can append requests to your master branch, the new commit will automatically add to this request

Awesome, thank you. It's changed.

**Pull request merged**
