### PR TITLE
Add VSEA testnet

### PR DESCRIPTION
**Pull request by Bread-VeSea**

### CODE REVIEW

**Review by XJWX89 — CHANGES_REQUESTED** [review]
hi @Bread-VeSea , the directory name(contract address) must be **lower cases**.

**Comment by Bread-VeSea** [comment]
Sorry about that @XJWX89 - it's been updated

**Review by XJWX89 — APPROVED** [review]
@Bread-VeSea , I forgot to mention that I found the `token name` is different between the PR(`VeSea Token`) and the contract(`VeSea`).  

I will approve this pr first, please make sure you fix it when you are adding the token to the mainnet

**Comment by Bread-VeSea** [comment]
Closing pull request as we are ready to submit mainnet

**Pull request closed without merging**
