### PR TITLE
Add WVET

### PR DESCRIPTION
**Pull request by xenide**

### CODE REVIEW

**Review by Zds23gbo — APPROVED** [review]

**Review by XJWX89 — CHANGES_REQUESTED** [review]
hi @xenide , please change the token icon due to  ***The likelihood of confusion may cause users hard to identify.***  Please do not directly use another company's  company's trademarks (icon, logo or name) without permission.

**Comment by xenide** [comment]
@XJWX89 changed the logo to something we designed ourselves. Can you review them again? Thanks.

**Comment by xenide** [comment]
@XJWX89 do you have any comments for us?

**Comment by XJWX89** [comment]
hi @xenide , sorry for the late reply. first of all please check the guideline that the token image should be named `token.png`.

second, the wrapped token required the following:
1. Contract needs open-sourced and provide compilation parameter. (**mandatory**)
2. Provide the audit report.(**mandatory**)
3. Provide an application that allows the user to convert (***VET< >WVET***) the token. (**mandatory**)
4. A way that user can claim the VTHO (**optional**)

**Comment by xenide** [comment]
closing as we're dropping the effort for this for now

**Pull request closed without merging**
