### PR TITLE
Bluegate-BS

### PR DESCRIPTION
**Pull request by samwelgichungu**
MDN is the Madini VeChain Vip180 token that is used to carry value or "smart money" from Madini smart contracts. In other words, transactions on decentralized applications occurring on Madini VeChain's blockchain will use MDN. It is available for investing by the general public. MDN token is the Madini utility token in our Ecosystem since it is linked to the Madini Minerals Marketplace, to the Madini VeChain Wallet - Android APP - and other Madini VeChain dApps,.

### CODE REVIEW

**Review by bluegatebs — APPROVED** [review]

**Review by bluegatebs — APPROVED** [review]

**Review by bluegatebs — APPROVED** [review]
Last version MDN Madini VIP180 approval

**Review by bluegatebs — APPROVED** [review]

**Review by bluegatebs — APPROVED** [review]

**Review by bluegatebs — APPROVED** [review]

**Review by bluegatebs — APPROVED** [review]

**Review by bluegatebs — APPROVED** [review]

**Review by bluegatebs — APPROVED** [review]

**Review by bluegatebs — APPROVED** [review]
Approve, merge and launch the VIP180 MDN

**Review by bluegatebs — APPROVED** [review]

**Review by bluegatebs — APPROVED** [review]

**Review by bluegatebs — APPROVED** [review]

**Review by bluegatebs — APPROVED** [review]

**Review by bluegatebs — APPROVED** [review]

**Review by bluegatebs — APPROVED** [review]

**Review by fpvigo — APPROVED** [review]

**Review by fpvigo — APPROVED** [review]

**Comment by XJWX89** [comment]
@samwelgichungu thanks for the submission , please check following things:
1.  please make sure the address is a contract
2. please remove the social media link if you do not have it. （twiter,telegram,facebook,medium,slack)
3. please check [apply to add token](https://vechain.typeform.com/to/ImOMvZ)

**Review by bluegatebs — APPROVED** [review]

**Review by fpvigo — APPROVED** [review]

**Review by fpvigo — APPROVED** [review]

**Comment by Zds23gbo** [comment]
Здравствуйте, мне хотелось узнать больше о смарт - контрактах, читаю комментарии, что то понятно что то нет, если я делаю не правильно не судите строго я без злого умысла, подскажите если что. Спасибо большое.

**Review by bluegatebs — APPROVED** [review]

**Review by fpvigo — APPROVED** [review]

**Comment by fpvigo** [comment]
> * please make sure the address is a contract   OK contract confirmed
> 
> * please remove the social media link if you do not have it. （twiter,telegram,facebook,medium,slack)  OK updated and clean
> 
> * please check [apply to add token](https://vechain.typeform.com/to/ImOMvZ)  OK Form completed and submitted

Thank you!! 🥇 :)

**Review by fpvigo — APPROVED** [review]

**Review by fpvigo — APPROVED** [review]

**Review by fpvigo — APPROVED** [review]
Approved and all info submitted for final MDN deploy

**Review by fpvigo — APPROVED** [review]

**Review by fpvigo — APPROVED** [review]

**Comment by Zds23gbo** [comment]
Хорошо

**Review by Zds23gbo — APPROVED** [review]

**Review by XJWX89 — APPROVED** [review]

**Pull request merged**
