### PR TITLE
add vex

### PR DESCRIPTION
**Pull request by KennethAshley**

### CODE REVIEW

**Comment by XJWX89** [comment]
@KennethAshley contract address must be lower case

**Review by XJWX89 — CHANGES_REQUESTED** [review]
HI @KennethAshley contract address must be lower case

**Comment by KennethAshley** [comment]
@XJWX89 fixed!

**Review by XJWX89 — CHANGES_REQUESTED** [review]
hi @KennethAshley, please make sure the token image is 256 x 256 pixel size

**Comment by Zds23gbo** [comment]
Хорошо.

**Review by XJWX89 — APPROVED** [review]

**Pull request merged**
