### PR TITLE
register VPU token from VPunks

### PR DESCRIPTION
**Pull request by vefam**

### CODE REVIEW

**Review by Zds23gbo — APPROVED** [review]

**Review by Zds23gbo — COMMENTED** [review]
tokens/main/0xb0821559723db89e0bd14fee81e13a3aae007e65/token.png

**Review by XJWX89 — APPROVED** [review]

**Comment by vefam** [comment]
@XJWX89 @libotony 
Thank you VeChain for merging VPU token registration.
Users are looking forward to seeing VPU on VeChainThor wallet, looking forward to your support, if I need to do anything else please let me know!

**Comment by XJWX89** [comment]
hi @vefam , here's the link of [apply to add token](https://form.typeform.com/to/ImOMvZ). Once it is approved, the user can see your token(VPU) on thorwallet. please let us know if you need further support

**Comment by vefam** [comment]
> 
> 
> hi @vefam , here's the link of [apply to add token](https://form.typeform.com/to/ImOMvZ). Once it is approved, the user can see your token(VPU) on thorwallet. please let us know if you need further support

@XJWX89 
Thanks you, we have applied!

**Pull request merged**
