### PR TITLE
ADD BVC

### PR DESCRIPTION
**Pull request by DennisD076**

### CODE REVIEW

**Comment by libotony** [comment]
Hi @DennisD076 I was wondering does BVC had a page at https://blackvemarket.com/ ?

**Comment by DennisD076** [comment]
Hi @libotony, yes that's true indeed. I should add the info right?

**Comment by libotony** [comment]
> Hi @libotony, yes that's true indeed. I should add the info right?

Yes, I would recommend add links.

**Comment by DennisD076** [comment]
Is should be done now! Thanks in advance

**Comment by libotony** [comment]
I noticed that the link GitHub was pointing to another account, I would like to ask if @Murtagh300 would authorize it.

**Review by libotony — APPROVED** [review]

**Review by XJWX89 — APPROVED** [review]

**Pull request merged**
