### PR TITLE
Add union token to token-registry

### PR DESCRIPTION
**Pull request by Scale0**

### CODE REVIEW

**Comment by Murtagh300** [comment]
@libotony Can you check this for us ? it is a fully functional already.

**Comment by XJWX89** [comment]
hi @Scale0 & @Murtagh300, sorry for the late review. 

Please rename the folder name, the contract **MUST BE lower cases**

Moreover, would you like to add more info about the token? (such as social media ), you can check the [example here](https://explore.vechain.org/accounts/0x0000000000000000000000000000456e65726779/)/ [add additional.json file](https://github.com/vechain/token-registry#generate-token-information).

**Review by XJWX89 — CHANGES_REQUESTED** [review]
hi @Scale0 & @Murtagh300, sorry for the late review. 

Please rename the folder name, the contract **MUST BE lower cases**

Moreover, would you like to add more info about the token? (such as social media ), you can check the [example here](https://explore.vechain.org/accounts/0x0000000000000000000000000000456e65726779/)/ [add additional.json file](https://github.com/vechain/token-registry#generate-token-information).

**Comment by Scale0** [comment]
Hi @XJWX89  thnx for the reply :),
do i need to close this PR and create a new one with the correct conventions? im not sure how to edit an existing PR.
I will do the changes/new PR later today, should just tag you in it?

**Review by XJWX89 — CHANGES_REQUESTED** [review]
hi @Scale0 , it seems that the testnet directory name still contain uppercase letters.

**Comment by Scale0** [comment]
hi @XJWX89 i wasnt finished yet, only changed a few characters, also the whitepaper link wasn't correct yet..
changed all for the good now :)

**Comment by XJWX89** [comment]
hi @Scale0, I ran a final check before approving this PR. base on the token info you provided, the token decimals on testnet is mismatch..... could you check it with devs?

**Comment by Scale0** [comment]
Hi @XJWX89  the developer deployed a new contract to testnet, i edited the directory names :)

**Review by libotony — APPROVED** [review]

**Review by XJWX89 — APPROVED** [review]

**Pull request merged**
