### PR TITLE
New LGCT

### PR DESCRIPTION
**Pull request by paulaamstutz**
New deployed addresses for both testnet and mainnet for LGCT

### CODE REVIEW

**Comment by paulaamstutz** [comment]
We had to redeploy the token in both mainnet and testnet due to an error that was occurring. Please accept this pull request with the new addresses, thank you!

**Comment by RsTs23** [comment]
The updated audit report (as a proof of redeployment) is attached. Please let us know if you need any further information.
[Legacy Token.Final.V2.pdf](https://github.com/vechain/token-registry/files/10696154/Legacy.Token.Final.V2.pdf)

**Review by XJWX89 — APPROVED** [review]

**Comment by libotony** [comment]
@paulaamstutz @RsTs23 Ping me here after your token get some activities, I'll add them to explorer

**Comment by RsTs23** [comment]
@libotony Hi, as you can see we start to have some initial activity on the token. https://vechainstats.com/token/lgct/#token-transfers
There is still more on the other chains but it will increase in due time. Could you add the token to the explorer please?

**Pull request merged**
