### PR TITLE
Add wrappedUSDC from bridge.vet

### PR DESCRIPTION
**Pull request by ifavo**
This Pull Requests adds a by bridge.vet managed wrapped version of USDC.
Un/Wrapping can be managed on https://bridge.vet and is processed through market buying/selling VET in favor of an BSC locked USDC version.

### CODE REVIEW

**Comment by libotony** [comment]
Hi @ifavo could you elaborate on how this Un/Wrapping is working?

**Comment by ifavo** [comment]
@libotony sure, to burn a wrapped token, it needs to be sold. The original token is sold at its current market value for VET.

Here's what happens during burning:
- The wrapped token is sent to bridge.vet
- bridge.vet changes the chosen token on Binance Smart Chain (BSC) into VET on Vechain
- The wrapped token is burned
- The VET is sent to the burner's wallet

The basic process is explained here as well: https://bridge.vet/about – if there is any interest, redemption/deposit without going thru VET is a future option.

**Comment by libotony** [comment]
> @libotony sure, to burn a wrapped token, it needs to be sold. The original token is sold at its current market value for VET.
> 
> Here's what happens during burning:
> 
> * The wrapped token is sent to bridge.vet
> * bridge.vet changes the chosen token on Binance Smart Chain (BSC) into VET on Vechain
> * The wrapped token is burned
> * The VET is sent to the burner's wallet
> 
> The basic process is explained here as well: https://bridge.vet/about – if there is any interest, redemption/deposit without going thru VET is a future option.

Thank you for the explanation, for approving this PR, can you provide the contract source and compiler options to verify the contract source code? We have additional requests regarding wrapped tokens.

I have some other questions related to your app bridge.vet(not related to approving this PR, like the work you have done, BTW):
+ Does this token follow this https://github.com/circlefin/stablecoin-evm/blob/master/doc/bridged_USDC_standard.md?
+ Is there a centralized service behind for Wrapping/Unwrapping USDC tokens on BSC?
+ Any considerations on securing user's funds on bridge.vet?

Again, we can first work on approving this PR, and then talk about your app.

**Comment by ifavo** [comment]
@libotony I am happy that you are open to approve the PR, because then it will be supported in the wallet by default, improving user experience.

Let me answer each:

1. The contract does not yet follow the linked standard (yet). Its an OZ-ERC20 contract with role management, to make sure its as simple as possible, same as vorj token deployments. The USDC standard came to my attention only after this PR was made, I already started to switch to the USDC standardized contract. Due truffles in the USDC project, I had troubles deploying it. I wanted to keep the PR open to see your willingness to approve. If you approve, I like to ask you to wait until the new contract is deployed, because it will change the address.
2. There is a centralized service behind the (un)wrapping, otherwise it won't be possible to accomplish this right now. The basic mean is to create a representation on Vechain for simple management, its goal is not to bring a fully wrapped token here, but to simplify the management without going cross-chain. The main goal is it to be part of the vtho.exchange auto swap feature.
3. Security breaks, as with every bridge or even L2, with the private keys that are required to be accessable for certain services. These are secured within the bridging service. If there will be some traction, a monitor will be implemented, that will auto-pause if something suspicious happens.

I'm happy to talk about it, as every input or question improves the way we think about things.

**Comment by libotony** [comment]
@ifavo I'll leave the PR open and wait for the new contract.

**Pull request closed without merging**
