### PR TITLE
Add Glo Dollar Token on Testnet

### PR DESCRIPTION
**Pull request by gglucass**

### CODE REVIEW

**Comment by libotony** [comment]
@gglucass The folder name should be in lowercase, could you please update?

**Comment by libotony** [comment]
Correct me if I am wrong, looks like https://www.glodollar.org/ is the official website to this token, would like add the link to this token?

**Comment by gglucass** [comment]
Thank you @libotony - both changes have been made :-)

**Comment by libotony** [comment]
@gglucass Please resize the image to 256px by 256px.

**Review by libotony — APPROVED** [review]

**Pull request merged**
